### ISSUE TITLE
Wrong CaseId being used in addResultForCase

### ISSUE THREAD

**Issue by maylortaylor** [automatekitbox/testrail-api-integration#2]
I got this library working, using the **AddResultForCase** function,  but whenever I pass in **caseId = 54** it will actually update case # 55.

If I update case # 40 -- i'll see case # 41 updated.

Why ?

I should not have to -1 to every caseId

**Comment by automatekitbox** [comment]
Sorry I could not see this issue,
Please provide the sample code snippet
version ?

**Comment by automatekitbox** [comment]
<img width="170" alt="Screenshot 2021-05-20 at 6 24 08 PM" src="https://user-images.githubusercontent.com/72825298/118982091-b3f0c380-b998-11eb-98b8-7011e957decc.png">
<img width="176" alt="Screenshot 2021-05-20 at 6 23 54 PM" src="https://user-images.githubusercontent.com/72825298/118982094-b5ba8700-b998-11eb-9796-1a0f5a9a495f.png">

**Comment by automatekitbox** [comment]
I hope you are providing caseid which starts with C , Ex: above caseid is 1

We should not provide testids which starts with T since it changes for each new test run
TestId is 4

**Comment by automatekitbox** [comment]
This  issue is not reproducible
